MT-1186 Adobe Visitor API
Tealium/tealium-react-native pull request #147
Opened 2023-01-20 00:02 UTC by tamayok

2023-01-20 14:54 UTC, jameskeith requested changes

2023-01-20 14:54 UTC, jameskeith commented on modules/adobe-visitor/android/src/main/java/com/tealiumreactadobevisitor/TealiumReactAdobeVisitor.kt
> +    private var _adobe_org_id: String? = null
these shouldn't have underscores in the names.

2023-01-20 14:54 UTC, jameskeith commented on modules/adobe-visitor/android/src/main/java/com/tealiumreactadobevisitor/TealiumReactAdobeVisitor.kt
> +    @ReactMethod
These `setXyz` methods do not need to be annotated with `@ReactMethod` since they are never intended to be called by ReactNative code, right?
Since they only write to a local var, I'd be happy to remove them.

2023-01-20 14:54 UTC, jameskeith commented on modules/adobe-visitor/common.ts
> +    adobeVisitorOrgId ?: string;
could argue for this to be required rather than nullable, since it's necessary for module to work properly

2023-01-20 14:54 UTC, jameskeith commented on modules/adobe-visitor/index.d.ts
> +        public static linkExistingEcidToKnownIdentifier(knownId: String, adobeDataProviderId: String, authState?: AuthState | number, callback?:(response: any) => void): void;
this method name diverges from the one in the underlying module:
`linkExistingEcidToKnownIdentifier`
vs
`linkEcidToKnownIdentifier`

2023-01-20 14:54 UTC, jameskeith commented on modules/adobe-visitor/index.d.ts
> +         * Resets current visitor
Javadoc needs updating

2023-01-20 14:54 UTC, jameskeith commented on modules/adobe-visitor/index.js
> +const ios = "ios"
are these used?

2023-01-20 14:54 UTC, jameskeith commented on modules/adobe-visitor/index.d.ts
> +        public static linkExistingEcidToKnownIdentifier(knownId: String, adobeDataProviderId: String, authState?: AuthState | number, callback?:(response: any) => void): void;
this method has `authState` and `callback` marked as nullable (correctly) but the implementation in Android has them non-nullable. 
It causes a crash if you try and call it without either parameter/ or with them set to null.

2023-01-20 14:54 UTC, jameskeith commented on modules/adobe-visitor/tealium-react-adobe-visitor.podspec
> +  s.license = { :type => "Commercial", :file => "LICENSE.txt" }
license file directive prompts a warning, filename is `LICENSE` without the `.txt` suffix

2023-01-20 14:54 UTC, jameskeith commented on modules/adobe-visitor/package.json
> +    "tealium-react-native": "^2.3.0"
Is `^2.3.0` correct?
The `podspec` file has a minimum version of `2.2.0` which I believe is when the `OptionalModules` were introduced (along with Location) - wondered if this can be lowered to `^2.2.0` to enable support for a larger set of users?

2023-01-20 14:54 UTC, jameskeith commented on modules/adobe-visitor/ios/TealiumReactAdobeVisitor.m
> +    RCT_EXTERN_METHOD(linkEcidToKnownIdentifier:(NSString)knownId adobeDataProviderId: (NSString)adobeDataProviderId authState: (nonnull NSNumber*)authState callback: (RCTResponseSenderBlock*)callbac
similar to Android, in that this stipulates the `authState` as `nonnull` despite the underlying Swift code not requiring it. 
App crashes if `authState` is not provided even though its marked optional in the typescript definitions.

2023-01-20 22:22 UTC, tamayok commented on modules/adobe-visitor/index.d.ts
> +        public static linkExistingEcidToKnownIdentifier(knownId: String, adobeDataProviderId: String, authState?: AuthState | number, callback?:(response: any) => void): void;
@jameskeith React Native does not let me pass in a null value for `int?`. In the enum for AuthState, I added a -1 for `undefined`. In kotlin, there's a check that if the state is -1 pass null, else use the authState value. I believe @trister1997 ran into the same issue.

2023-01-31 17:34 UTC, jameskeith requested changes

2023-01-31 17:34 UTC, jameskeith commented on modules/adobe-visitor/android/src/main/java/com/tealium/react/adobevisitor/TealiumReactAdobeVisitor.kt
> +            authState,
i think you may need to reinstate the original line here to ensure a `null` is passed when the value is invalid.
passing `-1` seems to trigger the `failure` callback every time for me, where `null` does not.

2023-01-31 17:34 UTC, jameskeith commented on modules/adobe-visitor/android/src/main/java/com/tealium/react/adobevisitor/TealiumReactAdobeVisitor.kt
> +            config.existingVisitorId = it
just spotted that this is pointing at the wrong prop - should be `config.adobeVisitorExistingEcid`

2023-01-31 17:34 UTC, jameskeith commented on modules/adobe-visitor/android/src/main/java/com/tealium/react/adobevisitor/TealiumReactAdobeVisitor.kt
> +            authState,
you may need to reinstate the previous version of this:
`if (authState == null) null else authState`
If I omit the `authState` param in the JS, and `-1` gets passed, then the `failure` callback happens for me every time, whereas `null` does not do so.

2023-01-31 17:34 UTC, jameskeith commented on modules/adobe-visitor/index.d.ts
> +         * @param config configuration properties for Adocbe Visitor module
typo on `Adocbe`

2023-01-31 17:34 UTC, jameskeith commented on modules/adobe-visitor/index.d.ts
> +         * Configres the Tealium Adobe Visitor module
typo on `Configres`

2023-01-31 17:34 UTC, jameskeith commented on modules/adobe-visitor/ios/TealiumReactAdobeVisitor.swift
> +                    callback([visitor])
Do you need to use the `visitor.encoded` property instead?
This always seems to fail for me - I always get the following in the console:
```
 LOG  AdobeVisitor Data: null
```
Debugging shows that the `visitorResult` does contain a valid AdobeVisitor object though

2023-02-03 15:39 UTC, jameskeith approved these changes

2023-02-06 19:19 UTC, merged